vision:
    # Indicates whether the vision module will process RGB images or ignore them.
    # true: process RGB images.
    # false: ignore RGB images.
    using_rgb: true

    # Indicates whether the vision module will process depth images or ignore them.
    # true: process depth images.
    # false: ignore depth images.
    using_depth: true

    homography:
        # Indicates whether the homography class needs to calibrate depth camera (relative to rgb camera)
        # true: calibrates the depth camera
        # false: no calibration required, calibration matrix is loaded from a separate file
        calibrate: false

        # If "calibrate" is active, indicates whether the homography class should overwrite the previous calibration
        # matrix
        overwrite_calib_matrix: false

        # Indicates whether the homography class needs to run the rectification algorithm, or load a pre-calculated
        # from a separate file.
        # NOTE: If "calibrate" is active, rectification will also be active regardless of this config
        # true: runs the rectification algorithm
        # false: loads the rectification matrix from a separate file
        rectify: false

        # If "rectify" is active, indicates whether the homography class should overwrite the previous rectification
        # matrix
        overwrite_rect_matrix: false

    preprocessor:
        # Show image with the results of preprocessing
        show_image: false

    segmenter:
        # Show image with the results of segmentation
        show_image: false

        # Show trackbars to manually set the minimum saturation and value for HSV segmentation.
        # true: Show trackbars.
        # false: Don't show trackbars.
        hsv_adjust: true

        # Minimum hue for HSV segmentation.
        hsv_min_h: 0

        # Maximum hue for HSV segmentation.
        hsv_max_h: 20

        # Minimum saturation for HSV segmentation.
        hsv_min_s: 112

        # Minimum value for HSV segmentation.
        hsv_min_v: 178

        # Show image with the results of depth segmentation
        # true: Show trackbars
        # false: Don't show trackbars
        show_depth_image: true

        # Show trackbar for depth segmentation adjustment
        # true: Show trackbars
        # false: Don't show trackbars
        depth_adjust: true

        # Treshold value
        depth_treshold: 2000

        # Depth threshold divider
        depth_treshold_divider: 56

        # Size Value
        size_value: 100

    tracker:
        # Show image with the results of tracking
        show_image: false

        # Select which method will be used to track the soccer field
        # Options: "rgb" or "depth"
        field_tracking_mode: "rgb"

        # The amount of frames in which the field center position has to be considered stable so as to stop tracking
        # the field.
        field_stabilization_frame: 7

        # The discrepancy allowed between each subsequent position so as to be considered the "same".
        field_center_discrepancy: 2

        # The amount of robots for each team (teams have the same amount of robots)
        robots_per_team: 1

        # Identification for the color representing our team. Can be either "Blue" or "Yellow"
        team: "Yellow"

    color:

        # Hue values for blue
        blue_min_h: 100
        blue_max_h: 150

        # Saturation values for blue
        blue_min_s: 133
        blue_max_s: 255

        # Value values for blue
        blue_min_v: 90
        blue_max_v: 255

        # Hue values for yellow
        yellow_min_h: 0
        yellow_max_h: 40

        # Saturation values for yellow
        yellow_min_s: 133
        yellow_max_s: 255

        # Value values for yellow
        yellow_min_v: 90
        yellow_max_v: 255

        # Hue values for red
        red_min_h: 150
        red_max_h: 200

        # Saturation values for red
        red_min_s: 133
        red_max_s: 255

        # Value values for red
        red_min_v: 90
        red_max_v: 255

        # Hue values for green
        green_min_h: 80
        green_max_h: 100

        # Saturation values for green
        green_min_s: 0
        green_max_s: 255

        # Value values for green
        green_min_v: 90
        green_max_v: 255

        # Hue values for purple
        purple_min_h: 120
        purple_max_h: 140

        # Saturation values for purple
        purple_min_s: 0
        purple_max_s: 255

        # Value values for purple
        purple_min_v: 90
        purple_max_v: 255

    gui:
        # Name of the RGB window
        rgb_window_name: "RGB frame"

        # Position of the RGB window
        rgb_window_pos_x: 0
        rgb_window_pos_y: 0

        # Name of the depth window
        depth_window_name: "Depth frame"

        # Position of the depth window
        depth_window_pos_x: 707
        depth_window_pos_y: 0

    measurement_conversion:
        # Width of the field, in metres
        field_width: 1.5

        # height of the field, in metres
        field_height: 1.3
